name: Execute Script

on:
  schedule:
    - cron: '*/10 * * * *'  # Run every 10 minutes

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Replace 'x' with the desired Python version

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install requests

    - name: Run Python script
      run: python monitor.py
