name: Execute Script

on:
  schedule:
    - cron: '*/1 * * * *'  # Run every minute

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Replace 'x' with the desired Python version

    - name: Install dependencies
      run: python -m pip install --upgrade pip && pip install csv requests

    - name: Run Python script
      run: python monitor.py  # Replace with the path to your Python script
